// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.16.0

package db

import (
	"context"
)

type Querier interface {
	CreateLoan(ctx context.Context, arg CreateLoanParams) (Loan, error)
	CreateLog(ctx context.Context, arg CreateLogParams) error
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	GetLoanByAccUsername(ctx context.Context, username string) ([]Loan, error)
	GetLogStats(ctx context.Context) ([]GetLogStatsRow, error)
	GetLogs(ctx context.Context) ([]Log, error)
	GetUser(ctx context.Context, username string) (User, error)
	GetUserByAccNo(ctx context.Context, accountNo string) (User, error)
	UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error)
}

var _ Querier = (*Queries)(nil)
